name: sihc
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn
  - joblib
  - pip
  - r-base=4.3
  - rpy2
  - r-remotes
  - r-mass
  - r-fastcluster
  - r-truncnorm
  - r-ggplot2
  - r-scales
  - r-dplyr
  - r-tibble
  - r-matrix
  - pip:
      - palmerpenguins